all : 
	gcc -Wtype-limits -Wcast-align -Wstrict-overflow -Wformat-security -Wformat -Wstrict-aliasing=3 -Wall -Wcast-align -lpthread -o ex1.exe ./src/ex1_main.c ./common/src/utils.c

clean :
	@echo "make: removing targets and objects of `pwd`"
